### ISSUE TITLE
prod keys on repo

### ISSUE THREAD

**Issue by KonixDev** [Penguin424/WHATSAPP_CRM#1]
Hi, i wanted to notice you that you have .env keys on your repo
if you are using those keys/credentials on real system (production) i will recommend you urgent remove .env from your github repo.

you must add a rule on your .gitignore in your visual studio code or something. 
Additionally, i think you added a cache files of your whatsapp session. it means if anyone download your repo can access to your whatsapp (i'm not 100% sure but you uploaded .wwebjs_cache folder. )

Edit: you have leaked your db access data! 
this is very dangerous if it is in production.

#https://github.com/Penguin424/WHATSAPP_CRM/blob/main/config/database.ts

if you don't want to change anything, change the privacy of your repo to private.

**Comment by Penguin424** [comment]
Thank you for noticing the errors even though it is not a project that you have in a production environment. I know how dangerous it is to have the keys and cache exposed. Thank you very much for pointing it out and sorry for the delay in seeing it. I hope you have a good day.
